//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAction()
        {
            this.tblUserActionMappings = new HashSet<tblUserActionMapping>();
        }
    
        public int ActionId { get; set; }
        public string ActionName { get; set; }
        public string ActionDisplayName { get; set; }
        public string ActionUrl { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public Nullable<bool> IsInMenu { get; set; }
        public Nullable<bool> IsView { get; set; }
        public Nullable<int> WorkShopId { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        public virtual tblModule tblModule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblUserActionMapping> tblUserActionMappings { get; set; }
    }
}
