//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBuyPartsFromSupplier
    {
        public int BuyId { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public Nullable<int> PartsId { get; set; }
        public Nullable<int> SupplierId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<int> Price { get; set; }
        public string Other { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> WorkShopId { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        public virtual tblStore tblStore { get; set; }
        public virtual tblPartsInfo tblPartsInfo { get; set; }
        public virtual tblSupplier tblSupplier { get; set; }
    }
}
