//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeInformation
    {
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeAddress { get; set; }
        public string ContactNumber { get; set; }
        public string EmployeeNid { get; set; }
        public string EmployeeNidImage { get; set; }
        public string EmployeeEmail { get; set; }
        public string EmployeeImage { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string DrivingLicenseImage { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<int> RouteId { get; set; }
        public Nullable<int> WorkShopId { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        public virtual tblDesignation tblDesignation { get; set; }
        public virtual tblRoute tblRoute { get; set; }
    }
}
