//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartsTransfer
    {
        public int PartsTransferId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> PartsId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> isIn { get; set; }
        public Nullable<bool> isOut { get; set; }
        public Nullable<int> WorkShopId { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        public virtual tblPartsInfo tblPartsInfo { get; set; }
        public virtual tblStore tblStore { get; set; }
    }
}
