//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserActionMapping
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public int action_id { get; set; }
        public Nullable<int> is_permitted { get; set; }
        public Nullable<int> agency_id { get; set; }
        public Nullable<int> WorkShopId { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tblAction tblAction { get; set; }
    }
}
