//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkShopUser
    {
        public decimal workShop_id { get; set; }
        public string UserId { get; set; }
        public decimal is_admin { get; set; }
        public Nullable<decimal> is_loggedIn { get; set; }
        public Nullable<System.DateTime> last_logged_time { get; set; }
        public string approve_by { get; set; }
        public Nullable<decimal> approve_date { get; set; }
        public Nullable<int> WorkShopId { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tblWorkShopInformation tblWorkShopInformation { get; set; }
    }
}
