//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWorkShopInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblWorkShopInformation()
        {
            this.tblWorkShopUsers = new HashSet<tblWorkShopUser>();
        }
    
        public decimal workShop_id { get; set; }
        public string Name { get; set; }
        public string short_name { get; set; }
        public string reg_Number { get; set; }
        public Nullable<System.DateTime> initial_date { get; set; }
        public string trec_number { get; set; }
        public Nullable<int> WorkShopId { get; set; }
        public string CreatedBy { get; set; }
        public string EditedBy { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
        public string Address { get; set; }
    
        public virtual tblWorkShopInformation tblWorkShopInformation1 { get; set; }
        public virtual tblWorkShopInformation tblWorkShopInformation2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWorkShopUser> tblWorkShopUsers { get; set; }
    }
}
